
name: main_workflow
on:
 push:
  branches:
   - nodejs_environment_job
jobs:
 checkout_code:
  strategy:
      matrix:
       node: [ '10', '12' ]
  runs-on: ubuntu-latest
  steps:
   - name: "Checkout code" 
     uses: actions/checkout@v2
   - name: Setting node version
     uses: actions/setup-node@v2
     with:
      node-version: ${{ matrix.node }}
   - name: "Linter execution"
     uses: github/super-linter@v3
     env:
      DEFAULT_BRANCH: nodejs_linter_job
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      LINTER_RULES_PATH: /
      JAVASCRIPT_ES_CONFIG_FILE: .eslintrc.json
      VALIDATE_JAVASCRIPT_ES: true
 test-execution:
    runs-on: ubuntu-latest
    needs: checkout_code
    steps:
        - name: "Checkout code" 
          uses: actions/checkout@v2
        - name: "Run jest tests"
          run: "npm install jest && npm test"
 nodejs_environment_job:
    runs-on: ubuntu-latest
    needs: [my_build, test-execution]
    env:
      DESTINATION_PERSON: '2DAW'
    steps:
      - name: adeloyedeji
        uses: adeloyedeji/github-actions-hello@v1.0
        with: 
          who-to-greet: '${{Env.DESTINATION_PERSON}}'

